module Emissary

  class NameSources

    attr_accessor :desert, :mountainous, :fantasy

    @@desert = [
      "Persepolis",
      "Susa",
      "Babylon",
      "Ecbatana",
      "Pasargadae",
      "Ctesiphon",
      "Ur",
      "Nineveh",
      "Arbela",
      "Nippur",
      "Larsa",
      "Shush",
      "Ekur",
      "Sippar",
      "Borsippa",
      "Uruk",
      "Lagash",
      "Eridu",
      "Isin",
      "Kish",
      "Agade",
      "Mashkan-shapir",
      "Adab",
      "Girsu",
      "Der",
      "Larsa",
      "Nuzi",
      "Mari",
      "Shuruppak",
      "Zabala",
      "Ziggurat",
      "Ahvaz",
      "Jiroft",
      "Eshnunna",
      "Qalatga Darband",
      "Gaochang",
      "Halaf",
      "Hatra",
      "Hissar",
      "Isfahan",
      "Jemdet Nasr",
      "Karum Kanesh",
      "Kerma",
      "Kunara",
      "Kurash",
      "Lagash",
      "Lalish",
      "Merv",
      "Meshginshahr",
      "Nimrud",
      "Palmyra",
      "Qabr Ishaq",
      "Qalatga Darband",
      "Qeshm",
      "Qurna",
      "Ray",
      "Shahr-i Sokhta",
      "Sharafabad",
      "Shimashki",
      "Shushtar",
      "Sikait",
      "Sistan",
      "Tang-e Sarvak",
      "Tepe Gawra",
      "Tepe Sialk",
      "Telloh",
      "Teppe Hasanlu",
      "Tepe Hissar",
      "Tepe Yahya",
      "Tishomingo",
      "Tureng Tepe",
      "Uruk",
      "Urfa",
      "Urartu",
      "Uruk",
      "Varamin",
      "Yasuj",
      "Yerevan",
      "Zabol",
      "Zanjan",
      "Zarzian",
      "Ziyaratgah",
      "Zuzan",
      "Qaladiza",
      "Baradost",
      "Chogha Zanbil",
      "Dasht-e Kavir",
      "Elam",
      "Firuzabad",
      "Gobekli Tepe",
      "Hawraman",
      "Kangavar",
      "Kharg Island",
      "Luristan",
      "Baghdad"
    ]

    @@mountainous = [
      "Valhalla",
      "Aalborg",
      "Aarhus",
      "Akureyri",
      "Alftanes",
      "Bergen",
      "Birka",
      "Björkö",
      "Borås",
      "Bork Havn",
      "Bornholm",
      "Esbjerg",
      "Fosnavåg",
      "Geiranger",
      "Gimli",
      "Gothenburg",
      "Hafnarfjörður",
      "Halmstad",
      "Hammerfest",
      "Helsingborg",
      "Helsingør",
      "Hudiksvall",
      "Húsavík",
      "Höfn",
      "Jelling",
      "Jönköping",
      "Keflavík",
      "Kópavogur",
      "Kristiansand",
      "Kristiansund",
      "Kungälv",
      "Larvik",
      "Lidingö",
      "Linköping",
      "Luleå",
      "Malmö",
      "Mariefred",
      "Marstrand",
      "Mjölby",
      "Mölndal",
      "Norrköping",
      "Nykøbing Falster",
      "Odense",
      "Öland",
      "Örebro",
      "Oslo",
      "Oulu",
      "Reykjavík",
      "Ribe",
      "Røros",
      "Roslagen",
      "Sigtuna",
      "Skagen",
      "Skara",
      "Skellefteå",
      "Skien",
      "Skövde",
      "Stavanger",
      "Stockholm",
      "Sundsvall",
      "Svendborg",
      "Tórshavn",
      "Trondheim",
      "Turku",
      "Uppsala",
      "Vaasa",
      "Västerås",
      "Växjö",
      "Viborg",
      "Vikingen",
      "Visby",
      "Voss",
      "Ystad",
      "Ålesund",
      "Århus",
      "Ängelholm",
      "Östersund"
    ]

    @@arid = [
      "Alcazar",
      "Algeciras",
      "Alhambra",
      "Almeria",
      "Antequera",
      "Arcos",
      "Baeza",
      "Benalmadena",
      "Cadiz",
      "Cordoba",
      "El Ejido",
      "Fez",
      "Gibraltar",
      "Granada",
      "Guadix",
      "Jerez",
      "Larache",
      "Malaga",
      "Marrakech",
      "Medina Sidonia",
      "Meknes",
      "Melilla",
      "Mogador",
      "Essaouira",
      "Montilla",
      "Motril",
      "Nador",
      "Nerja",
      "Oujda",
      "Ronda",
      "Sale",
      "Sebta",
      "Ceuta",
      "Setenil",
      "Tanger",
      "Tarifa",
      "Tetouan",
      "Torremolinos",
      "Ubeda",
      "Vejer",
      "Xativa",
      "Xirivella",
      "Xixona",
      "Yebes",
      "Zahara",
      "Zafarraya",
      "Zafra",
      "Zalamea",
      "Zagra",
      "Zaidin",
      "Zamarramala",
      "Zamora"
    ]

    @@forested = [
      "Aberystwyth",
      "Aberdare",
      "Aberavon",
      "Aberbargoed",
      "Aberbeeg",
      "Abercarn",
      "Aberdaron",
      "Aberdour",
      "Aberdyfi",
      "Aberfan",
      "Abergavenny",
      "Abergwaun",
      "Aberhosan",
      "Aberkenfig",
      "Aberllefenni",
      "Abermawr",
      "Abermule",
      "Abersoch",
      "Abertridwr",
      "Aberystwyth",
      "Afonwen",
      "Beddgelert",
      "Bedwas",
      "Betws",
      "Blaenau",
      "Bodffordd",
      "Bontnewydd",
      "Borth",
      "Braichmelyn",
      "Bryncoch",
      "Caernarfon",
      "Caerphilly",
      "Capel",
      "Carmarthen",
      "Ceinws",
      "Cilgerran",
      "Conwy",
      "Corwen",
      "Criccieth",
      "Cwm",
      "Dinas",
      "Dolgellau",
      "Dre-fach",
      "Efailwen",
      "Ffair-fach",
      "Ffestiniog",
      "Fishguard",
      "Gell",
      "Glyn",
      "Graig",
      "Grosmont",
      "Gwaenysgor",
      "Gwernogle",
      "Gwyddelwern",
      "Gwynedd",
      "Harlech",
      "Henllan",
      "Llan",
      "Llandaff",
      "Llanddewi",
      "Llandeilo",
      "Llandovery",
      "Llandrindod",
      "Llandudno",
      "Llandwrog",
      "Llanelli",
      "Llanerch",
      "Llanfair",
      "Llanfihangel",
      "Llanfyllin",
      "Llangadog",
      "Llangain",
      "Llangefni",
      "Llangollen",
      "Llanidloes",
      "Llanishen",
      "Llanrwst",
      "Llansamlet",
      "Llantwit",
      "Llanwrtyd",
      "Llwyngwril",
      "Maenan",
      "Maesteg",
      "Menai",
      "Merthyr",
      "Moelfre",
      "Nant",
      "Nefyn",
      "Penarth",
      "Penmaenmawr",
      "Pontarddulais",
      "Pontardawe",
      "Pontypool",
      "Pontypridd",
      "Porthcawl",
      "Pwllheli",
      "Rhos",
      "Rhyd",
      "Rhydcymerau",
      "Rhydlewis",
      "Rhydymwyn",
      "Talsarnau",
      "Talybont",
      "Trawsfynydd",
      "Tredegar",
      "Trefor",
      "Tregaron",
      "Treherbert",
      "Treharris",
      "Treorchy",
      "Tresaith",
      "Tycroes",
      "Tywyn",
      "Ynys",
      "Ystrad"
    ]

    @@maritime  = [
      "Arezzo",
      "Ascoli Piceno",
      "Bergamo",
      "Bologna",
      "Città di Castello",
      "Faenza",
      "Ferrara",
      "Florence",
      "Forlì",
      "Genoa",
      "Lucca",
      "Mantua",
      "Milan",
      "Modena",
      "Naples",
      "Orvieto",
      "Padua",
      "Parma",
      "Perugia",
      "Pisa",
      "Ravenna",
      "Rimini",
      "Rome",
      "Salò",
      "Siena",
      "Syracuse",
      "Trento",
      "Urbino",
      "Venice",
      "Verona",
      "Vicenza",
      "Alba",
      "Alessandria",
      "Ancona",
      "Arezzo",
      "Asti",
      "Benevento",
      "Brescia",
      "Cesena",
      "Cividale",
      "Cremona",
      "Fano",
      "Fermo",
      "Foligno",
      "Gubbio",
      "Imola",
      "Ivrea",
      "Lodi",
      "Massa Marittima",
      "Novara",
      "Pavia",
      "Pesaro",
      "Pistoia",
      "Prato",
      "Rieti",
      "San Gimignano",
      "Sassari",
      "Savona",
      "Sondrio",
      "Spoleto",
      "Teramo",
      "Todi",
      "Tortona",
      "Treviso",
      "Vercelli",
      "Viterbo",
      "Alviano",
      "Boboli",
      "Calcata",
      "Casciana Terme",
      "Cetona",
      "Colle di Val d'Elsa",
      "Corciano",
      "Fiesole",
      "Gavorrano",
      "Magione",
      "Montalcino",
      "Montefalco",
      "Montepulciano",
      "Passignano sul Trasimeno",
      "Pitigliano",
      "San Quirico d'Orcia",
      "Santa Fiora",
      "Suvereto",
      "Valiano",
      "Vinci"
    ]

    @@lowland = [
      'Silberburg',
      'Eichenwald',
      'Falkenrath',
      'Rosenheim',
      'Hohenstein',
      'Adlerfurt',
      'Steinburg',
      'Wolfsburg',
      'Eisenberg',
      'Sonnenfeld',
      'Ritterstadt',
      'Goldenthal',
      'Falkenheim',
      'Drachenburg',
      'Silberbach',
      'Waldmeer',
      'Rosenburg',
      'Hirschstadt',
      'Turmhafen',
      'Sternenhof',
      'Elmsburg',
      'Falkenhorst',
      'Eibenwald',
      'Morgenstern',
      'Silbersee',
      'Adlerstein',
      'Rosental',
      'Hohenfels',
      'Drachental',
      'Sonnenberg',
      'Königsruh',
      'Falkensee',
      'Eichenhorst',
      'Wolkenburg',
      'Silberstein',
      'Rosenwald',
      'Hirschfeld',
      'Falkenfeld',
      'Eichenmeer',
      'Hohenwald',
      'Sternenstadt',
      'Drachenfeld',
      'Goldensee',
      'Silberthal',
      'Falkenhof',
      'Adlersberg',
      'Rosenfels',
      'Hohenruh',
      'Wolkenstadt',
      'Eibenfels',
      'Morgenwald',
      'Silberhorst',
      'Ritterburg',
      'Falkenrast',
      'Rosenmeer',
      'Hirschhorst',
      'Steinwald',
      'Wolkenhorst',
      'Adlerhorst',
      'Drachenmeer',
      'Silberstadt',
      'Eibenstadt',
      'Hohenmeer',
      'Rosental',
      'Falkental',
      'Ritterhorst',
      'Wolkenfeld',
      'Adlerstadt',
      'Drachenwald',
      'Silberhorst',
      'Hohenbach',
      'Rosenbach',
      'Falkenbach',
      'Eichenbach',
      'Adlersbach',
      'Drachenbach',
      'Sternenbach',
      'Silberbach',
      'Hirschbach',
      'Wolkenbach',
      'Eibenbach',
      'Falkenfurt',
      'Rosenfurt',
      'Hohenfurt',
      'Drachenfurt',
      'Silberfurt',
      'Adlerfurt',
      'Sternenfurt',
      'Ritterfurt',
      'Goldfurt',
      'Wolkenfurt',
      'Hirschfurt',
      'Eibenfurt',
      'Falkenheim',
      'Rosenheim',
      'Hohenheim',
      'Drachenheim',
      'Silberheim',
      'Adlerheim',
      'Sternenheim'
    ]

    def for_culture(culture)
      return @@desert if culture == :desert
      return @@mountainous if culture == :mountainous
      return @@arid if culture == :arid
      return @@forested if culture == :forested
      return @@maritime if culture == :maritime
      return @@lowland if culture == :lowland
    end

    def self.data_for_fantasy

      start_words = [
        "Dún",
        "Kjer",
        "Kirchen",
        "Ash",
        "Axe",
        "Exe",
        "Usk",
        "Esk",
        "Beck",
        "Bach",
        "Ben",
        "Beinn",
        "Beann",
        "Ban",
        "Ard",
        "Berry",
        "Berg",
        "Bex",
        "Blaen",
        "Crag",
        "Craig",
        "Gart",
        "Keld",
        "Knock",
        "Ling",
        "Stow",
        "Traeth",
        "Weald",
        "Aber",
        "Ast",
        "Auch",
        "Bal",
        "Brad",
        "Caer",
        "Dal",
        "Drum",
        "Dun",
        "Dum",
        "Don",
        "Inver",
        "Kil",
        "Kin",
        "Lang",
        "Nant",
        "Nor",
        "Pont",
        "Shep",
        "Stam",
        "Stan",
        "Wraith",
        "Gloom",
        "Sud",
        "Wes",
        "Win",
        "Llan",
        "Pen",
        "Rams",
        "Lynn",
        "Ost"
      ]

      end_words = [
        "druin",
        "wald",
        "dorf",
        "stein",
        "röd",
        "rød",
        "brück",
        "veld",
        "fjord",
        "hafen",
        "heim",
        "hoff",
        "hove",
        "holm",
        "berg",
        "berg",
        "bergen",
        "afon",
        "bergh",
        "bourne",
        "burn",
        "clere",
        "combe",
        "coombe",
        "coed",
        "crag",
        "each",
        "bridge",
        "castle",
        "eig",
        "firth",
        "ford",
        "forth",
        "ffordd",
        "fos",
        "foss",
        "gate",
        "garth",
        "garde",
        "gill",
        "glyn",
        "hithe",
        "hythe",
        "holm",
        "hurst",
        "keld",
        "lough",
        "magna",
        "mawr",
        "mere",
        "more",
        "moss",
        "stow",
        "dreath",
        "tun",
        "ton",
        "wold",
        "burgh",
        "bury",
        "shaw",
        "bost",
        "carden",
        "cott",
        "dale",
        "den",
        "dean",
        "don",
        "caster",
        "field",
        "frith",
        "ham",
        "hays",
        "ing",
        "krth",
        "cheth",
        "mouth",
        "ness",
        "port",
        "stead",
        "ster",
        "thwaite",
        "wick",
        "wich",
        "wych",
        "wyke",
        "ay",
        "scar",
        "thorn",
        "drim",
        "rath",
        "toft",
        "worth",
        "worthy",
        "wardine",
        "skeld",
        "grath"
      ]

      {
        prefixes: [],
        suffixes: [],
        base_words: [],
        starts: start_words,
        middles: [],
        ends: end_words,
        prefix_frequency: 0,
        suffix_frequency: 0,
        syllable_lengths: {0 => 1},
        source: []
      }

    end

  end

end