module Emissary

  class NameSources

    attr_accessor :desert, :mountainous, :fantasy

    @@desert = [
      "Persepolis",
      "Susa",
      "Babylon",
      "Ecbatana",
      "Pasargadae",
      "Ctesiphon",
      "Ur",
      "Nineveh",
      "Arbela",
      "Nippur",
      "Larsa",
      "Shush",
      "Ekur",
      "Sippar",
      "Borsippa",
      "Uruk",
      "Lagash",
      "Eridu",
      "Isin",
      "Kish",
      "Agade",
      "Mashkan-shapir",
      "Adab",
      "Girsu",
      "Der",
      "Larsa",
      "Nuzi",
      "Mari",
      "Shuruppak",
      "Zabala",
      "Ziggurat",
      "Ahvaz",
      "Jiroft",
      "Eshnunna",
      "Qalatga Darband",
      "Gaochang",
      "Halaf",
      "Hatra",
      "Hissar",
      "Isfahan",
      "Jemdet Nasr",
      "Karum Kanesh",
      "Kerma",
      "Kunara",
      "Kurash",
      "Lagash",
      "Lalish",
      "Merv",
      "Meshginshahr",
      "Nimrud",
      "Palmyra",
      "Qabr Ishaq",
      "Qalatga Darband",
      "Qeshm",
      "Qurna",
      "Ray",
      "Shahr-i Sokhta",
      "Sharafabad",
      "Shimashki",
      "Shushtar",
      "Sikait",
      "Sistan",
      "Tang-e Sarvak",
      "Tepe Gawra",
      "Tepe Sialk",
      "Telloh",
      "Teppe Hasanlu",
      "Tepe Hissar",
      "Tepe Yahya",
      "Tishomingo",
      "Tureng Tepe",
      "Uruk",
      "Urfa",
      "Urartu",
      "Uruk",
      "Varamin",
      "Yasuj",
      "Yerevan",
      "Zabol",
      "Zanjan",
      "Zarzian",
      "Ziyaratgah",
      "Zuzan",
      "Qaladiza",
      "Baradost",
      "Chogha Zanbil",
      "Dasht-e Kavir",
      "Elam",
      "Firuzabad",
      "Gobekli Tepe",
      "Hawraman",
      "Kangavar",
      "Kharg Island",
      "Luristan",
      "Baghdad",
      # Silk Road / Central Asia
      "Samarkand",
      "Bukhara",
      "Nishapur",
      "Herat",
      "Balkh",
      "Khiva",
      "Termez",
      "Urgench",
      "Dunhuang",
      "Kashgar",
      "Turfan",
      "Ghazni",
      "Kandahar",
      # Arabian Peninsula
      "Petra",
      "Aden",
      "Muscat",
      "Sohar",
      "Salalah",
      "Marib",
      "Hormuz",
      # Nubian / Egyptian
      "Thebes",
      "Memphis",
      "Meroe",
      "Napata",
      "Tanis",
      "Abydos",
      "Akhetaten",
      # More ancient Mesopotamia
      "Assur",
      "Ebla",
      "Tuttul",
      "Kalhu",
      "Arrapha",
      "Harappa",
      "Lothal",
      "Dholavira"
    ]

    @@mountainous = [
      "Valhalla",
      "Aalborg",
      "Aarhus",
      "Akureyri",
      "Alftanes",
      "Bergen",
      "Birka",
      "Björkö",
      "Borås",
      "Bork Havn",
      "Bornholm",
      "Esbjerg",
      "Fosnavåg",
      "Geiranger",
      "Gimli",
      "Gothenburg",
      "Hafnarfjörður",
      "Halmstad",
      "Hammerfest",
      "Helsingborg",
      "Helsingør",
      "Hudiksvall",
      "Húsavík",
      "Höfn",
      "Jelling",
      "Jönköping",
      "Keflavík",
      "Kópavogur",
      "Kristiansand",
      "Kristiansund",
      "Kungälv",
      "Larvik",
      "Lidingö",
      "Linköping",
      "Luleå",
      "Malmö",
      "Mariefred",
      "Marstrand",
      "Mjölby",
      "Mölndal",
      "Norrköping",
      "Nykøbing Falster",
      "Odense",
      "Öland",
      "Örebro",
      "Oslo",
      "Oulu",
      "Reykjavík",
      "Ribe",
      "Røros",
      "Roslagen",
      "Sigtuna",
      "Skagen",
      "Skara",
      "Skellefteå",
      "Skien",
      "Skövde",
      "Stavanger",
      "Stockholm",
      "Sundsvall",
      "Svendborg",
      "Tórshavn",
      "Trondheim",
      "Turku",
      "Uppsala",
      "Vaasa",
      "Västerås",
      "Växjö",
      "Viborg",
      "Vikingen",
      "Visby",
      "Voss",
      "Ystad",
      "Ålesund",
      "Århus",
      "Ängelholm",
      "Östersund",
      # More Norwegian
      "Arendal",
      "Bodø",
      "Drammen",
      "Fredrikstad",
      "Gjøvik",
      "Hamar",
      "Harstad",
      "Kongsberg",
      "Molde",
      "Namsos",
      "Narvik",
      "Sandefjord",
      "Sarpsborg",
      "Lillehammer",
      "Porsgrunn",
      # Finnish
      "Helsinki",
      "Tampere",
      "Lahti",
      "Jyväskylä",
      "Kuopio",
      "Rovaniemi",
      "Joensuu",
      "Kajaani",
      "Pori",
      "Rauma",
      "Hämeenlinna",
      "Kouvola",
      # More Icelandic
      "Borgarnes",
      "Dalvík",
      "Egilsstaðir",
      "Ísafjörður",
      "Selfoss",
      "Sauðárkrókur",
      "Siglufjörður",
      # More Danish
      "Fredericia",
      "Horsens",
      "Randers",
      "Silkeborg",
      "Vejle",
      "Holbæk",
      "Næstved",
      "Kolding"
    ]

    @@arid = [
      "Alcazar",
      "Algeciras",
      "Alhambra",
      "Almeria",
      "Antequera",
      "Arcos",
      "Baeza",
      "Benalmadena",
      "Cadiz",
      "Cordoba",
      "El Ejido",
      "Fez",
      "Gibraltar",
      "Granada",
      "Guadix",
      "Jerez",
      "Larache",
      "Malaga",
      "Marrakech",
      "Medina Sidonia",
      "Meknes",
      "Melilla",
      "Mogador",
      "Essaouira",
      "Montilla",
      "Motril",
      "Nador",
      "Nerja",
      "Oujda",
      "Ronda",
      "Sale",
      "Sebta",
      "Ceuta",
      "Setenil",
      "Tanger",
      "Tarifa",
      "Tetouan",
      "Torremolinos",
      "Ubeda",
      "Vejer",
      "Xativa",
      "Xirivella",
      "Xixona",
      "Yebes",
      "Zahara",
      "Zafarraya",
      "Zafra",
      "Zalamea",
      "Zagra",
      "Zaidin",
      "Zamarramala",
      "Zamora",
      "Agadir",
      "Alcazarquivir",
      "Alicante",
      "Almodovar",
      "Asilah",
      "Azrou",
      "Badajoz",
      "Baza",
      "Beni Mellal",
      "Caceres",
      "Carmona",
      "Chefchaouen",
      "Coin",
      "Ecija",
      "Errachidia",
      "Fuengirola",
      "Guelmin",
      "Huelva",
      "Ifrane",
      "Jaen",
      "Khenifra",
      "Loja",
      "Lucena",
      "Marbella",
      "Merida",
      "Midelt",
      "Mijas",
      "Montoro",
      "Moulay Idriss",
      "Murcia",
      "Osuna",
      "Ouarzazate",
      "Priego",
      "Safi",
      "Sefrou",
      "Taroudant",
      "Taza",
      "Tinghir",
      "Tiznit",
      "Valencia",
      "Zagora",
      # Tunisian
      "Kairouan",
      "Sfax",
      "Sousse",
      "El Jem",
      "Tozeur",
      "Gafsa",
      "Gabès",
      "Monastir",
      "Mahdia",
      "Bizerte",
      "Nabeul",
      "Hammamet",
      # Classical Libyan / North African
      "Leptis Magna",
      "Sabratha",
      "Cyrene",
      "Apollonia",
      "Berenice",
      "Ptolemais",
      # More Iberian
      "Tortosa",
      "Lerida",
      "Orihuela",
      "Cuenca",
      "Almaden",
      "Plasencia",
      "Trujillo",
      "Zaragoza",
      "Teruel"
    ]

    @@forested = [
      "Aberystwyth",
      "Aberdare",
      "Aberavon",
      "Aberbargoed",
      "Aberbeeg",
      "Abercarn",
      "Aberdaron",
      "Aberdour",
      "Aberdyfi",
      "Aberfan",
      "Abergavenny",
      "Abergwaun",
      "Aberhosan",
      "Aberkenfig",
      "Aberllefenni",
      "Abermawr",
      "Abermule",
      "Abersoch",
      "Abertridwr",
      "Aberystwyth",
      "Afonwen",
      "Beddgelert",
      "Bedwas",
      "Betws",
      "Blaenau",
      "Bodffordd",
      "Bontnewydd",
      "Borth",
      "Braichmelyn",
      "Bryncoch",
      "Caernarfon",
      "Caerphilly",
      "Capel",
      "Carmarthen",
      "Ceinws",
      "Cilgerran",
      "Conwy",
      "Corwen",
      "Criccieth",
      "Cwm",
      "Dinas",
      "Dolgellau",
      "Dre-fach",
      "Efailwen",
      "Ffair-fach",
      "Ffestiniog",
      "Fishguard",
      "Gell",
      "Glyn",
      "Graig",
      "Grosmont",
      "Gwaenysgor",
      "Gwernogle",
      "Gwyddelwern",
      "Gwynedd",
      "Harlech",
      "Henllan",
      "Llan",
      "Llandaff",
      "Llanddewi",
      "Llandeilo",
      "Llandovery",
      "Llandrindod",
      "Llandudno",
      "Llandwrog",
      "Llanelli",
      "Llanerch",
      "Llanfair",
      "Llanfihangel",
      "Llanfyllin",
      "Llangadog",
      "Llangain",
      "Llangefni",
      "Llangollen",
      "Llanidloes",
      "Llanishen",
      "Llanrwst",
      "Llansamlet",
      "Llantwit",
      "Llanwrtyd",
      "Llwyngwril",
      "Maenan",
      "Maesteg",
      "Menai",
      "Merthyr",
      "Moelfre",
      "Nant",
      "Nefyn",
      "Penarth",
      "Penmaenmawr",
      "Pontarddulais",
      "Pontardawe",
      "Pontypool",
      "Pontypridd",
      "Porthcawl",
      "Pwllheli",
      "Rhos",
      "Rhyd",
      "Rhydcymerau",
      "Rhydlewis",
      "Rhydymwyn",
      "Talsarnau",
      "Talybont",
      "Trawsfynydd",
      "Tredegar",
      "Trefor",
      "Tregaron",
      "Treherbert",
      "Treharris",
      "Treorchy",
      "Tresaith",
      "Tycroes",
      "Tywyn",
      "Ynys",
      "Ystrad",
      # Breton (shares Celtic phonetic patterns with Welsh)
      "Quimper",
      "Douarnenez",
      "Concarneau",
      "Morlaix",
      "Landerneau",
      "Lesneven",
      "Quimperlé",
      "Pontivy",
      "Guingamp",
      "Lannion",
      "Roscoff",
      "Carhaix",
      "Paimpol",
      "Dinan",
      "Guémené",
      "Rostrenen",
      "Châteaulin",
      # Cornish
      "Bodmin",
      "Camborne",
      "Helston",
      "Penzance",
      "Redruth",
      "Truro",
      "Padstow",
      "Lostwithiel",
      "Penryn",
      "Liskeard",
      "Launceston",
      # Scottish Gaelic
      "Dingwall",
      "Invergordon",
      "Kingussie",
      "Strathpeffer",
      "Lochinver",
      "Golspie",
      "Dornoch",
      "Helmsdale",
      "Lairg",
      "Tain",
      "Brora",
      "Tongue"
    ]

    @@maritime  = [
      "Arezzo",
      "Ascoli Piceno",
      "Bergamo",
      "Bologna",
      "Città di Castello",
      "Faenza",
      "Ferrara",
      "Florence",
      "Forlì",
      "Genoa",
      "Lucca",
      "Mantua",
      "Milan",
      "Modena",
      "Naples",
      "Orvieto",
      "Padua",
      "Parma",
      "Perugia",
      "Pisa",
      "Ravenna",
      "Rimini",
      "Rome",
      "Salò",
      "Siena",
      "Syracuse",
      "Trento",
      "Urbino",
      "Venice",
      "Verona",
      "Vicenza",
      "Alba",
      "Alessandria",
      "Ancona",
      "Arezzo",
      "Asti",
      "Benevento",
      "Brescia",
      "Cesena",
      "Cividale",
      "Cremona",
      "Fano",
      "Fermo",
      "Foligno",
      "Gubbio",
      "Imola",
      "Ivrea",
      "Lodi",
      "Massa Marittima",
      "Novara",
      "Pavia",
      "Pesaro",
      "Pistoia",
      "Prato",
      "Rieti",
      "San Gimignano",
      "Sassari",
      "Savona",
      "Sondrio",
      "Spoleto",
      "Teramo",
      "Todi",
      "Tortona",
      "Treviso",
      "Vercelli",
      "Viterbo",
      "Alviano",
      "Boboli",
      "Calcata",
      "Casciana Terme",
      "Cetona",
      "Colle di Val d'Elsa",
      "Corciano",
      "Fiesole",
      "Gavorrano",
      "Magione",
      "Montalcino",
      "Montefalco",
      "Montepulciano",
      "Passignano sul Trasimeno",
      "Pitigliano",
      "San Quirico d'Orcia",
      "Santa Fiora",
      "Suvereto",
      "Valiano",
      "Vinci",
      # Southern Italian
      "Amalfi",
      "Bari",
      "Brindisi",
      "Cagliari",
      "Catania",
      "Gaeta",
      "Lecce",
      "Messina",
      "Otranto",
      "Palermo",
      "Salerno",
      "Taranto",
      "Trani",
      "Reggio",
      "Cosenza",
      # Greek Aegean
      "Corinth",
      "Argos",
      "Patras",
      "Nafplio",
      "Monemvasia",
      "Thessaloniki",
      "Kavala",
      "Chalcis",
      "Naupaktos",
      "Gythion",
      # Dalmatian coast
      "Dubrovnik",
      "Split",
      "Zadar",
      "Trogir",
      "Kotor",
      "Sibenik",
      "Hvar",
      "Korcula"
    ]

    @@lowland = [
      'Silberburg',
      'Eichenwald',
      'Falkenrath',
      'Rosenheim',
      'Hohenstein',
      'Adlerfurt',
      'Steinburg',
      'Wolfsburg',
      'Eisenberg',
      'Sonnenfeld',
      'Ritterstadt',
      'Goldenthal',
      'Falkenheim',
      'Drachenburg',
      'Silberbach',
      'Waldmeer',
      'Rosenburg',
      'Hirschstadt',
      'Turmhafen',
      'Sternenhof',
      'Elmsburg',
      'Falkenhorst',
      'Eibenwald',
      'Morgenstern',
      'Silbersee',
      'Adlerstein',
      'Rosental',
      'Hohenfels',
      'Drachental',
      'Sonnenberg',
      'Königsruh',
      'Falkensee',
      'Eichenhorst',
      'Wolkenburg',
      'Silberstein',
      'Rosenwald',
      'Hirschfeld',
      'Falkenfeld',
      'Eichenmeer',
      'Hohenwald',
      'Sternenstadt',
      'Drachenfeld',
      'Goldensee',
      'Silberthal',
      'Falkenhof',
      'Adlersberg',
      'Rosenfels',
      'Hohenruh',
      'Wolkenstadt',
      'Eibenfels',
      'Morgenwald',
      'Silberhorst',
      'Ritterburg',
      'Falkenrast',
      'Rosenmeer',
      'Hirschhorst',
      'Steinwald',
      'Wolkenhorst',
      'Adlerhorst',
      'Drachenmeer',
      'Silberstadt',
      'Eibenstadt',
      'Hohenmeer',
      'Rosental',
      'Falkental',
      'Ritterhorst',
      'Wolkenfeld',
      'Adlerstadt',
      'Drachenwald',
      'Silberhorst',
      'Hohenbach',
      'Rosenbach',
      'Falkenbach',
      'Eichenbach',
      'Adlersbach',
      'Drachenbach',
      'Sternenbach',
      'Silberbach',
      'Hirschbach',
      'Wolkenbach',
      'Eibenbach',
      'Falkenfurt',
      'Rosenfurt',
      'Hohenfurt',
      'Drachenfurt',
      'Silberfurt',
      'Adlerfurt',
      'Sternenfurt',
      'Ritterfurt',
      'Goldfurt',
      'Wolkenfurt',
      'Hirschfurt',
      'Eibenfurt',
      'Falkenheim',
      'Rosenheim',
      'Hohenheim',
      'Drachenheim',
      'Silberheim',
      'Adlerheim',
      'Sternenheim',
      # Real German — adds variety to the syllable pools
      'Augsburg',
      'Bamberg',
      'Coburg',
      'Dortmund',
      'Erfurt',
      'Frankfurt',
      'Goslar',
      'Hamburg',
      'Hannover',
      'Heidelberg',
      'Hildesheim',
      'Kassel',
      'Koblenz',
      'Leipzig',
      'Lüneburg',
      'Magdeburg',
      'Mainz',
      'Mannheim',
      'Marburg',
      'Nürnberg',
      'Passau',
      'Quedlinburg',
      'Regensburg',
      'Rothenburg',
      'Schwerin',
      'Soest',
      'Stralsund',
      'Trier',
      'Ulm',
      'Würzburg',
      # Dutch / Flemish / Hanseatic
      'Arnhem',
      'Breda',
      'Delft',
      'Deventer',
      'Dordrecht',
      'Groningen',
      'Haarlem',
      'Kampen',
      'Leiden',
      'Maastricht',
      'Middelburg',
      'Nijmegen',
      'Utrecht',
      'Venlo',
      'Zutphen',
      'Zwolle',
      'Lübeck',
      'Rostock',
      'Wismar',
      'Greifswald'
    ]

    # First and second elements for lowland compound family names (Option B).
    # Drawn from patterns in @@lowland source words.
    LOWLAND_FAMILY_FIRSTS = [
      "Silber", "Eichen", "Falken", "Rosen", "Hohen", "Adler",
      "Stein", "Eisen", "Sonnen", "Ritter", "Golden", "Drachen",
      "Wald", "Hirsch", "Turm", "Sternen", "Eiben", "Morgen",
      "Wolken", "Königs", "Gold", "Wolfs", "Elms", "Dorn"
    ]

    LOWLAND_FAMILY_SECONDS = [
      "burg", "wald", "rath", "heim", "stein", "furt", "berg",
      "feld", "bach", "meer", "stadt", "hafen", "hof", "horst",
      "see", "tal", "thal", "fels", "ruh", "mark", "stern", "rode"
    ]

    # Given names for minor noble knights, by culture.
    # Used by Names#get_knight_name to produce titles like "Sir Aldric" or "Ritter Wolfram".
    KNIGHT_NAMES = {
      desert: %w[
        Tariq Khalid Omar Hassan Rashid Malik Samir Yusuf Ibrahim Zaid
        Faris Qadir Jafar Karim Nasir Hamid Jalal Munir Salim Tahir
        Bilal Dawud Harun Ismail Sulayman
      ],
      arid: %w[
        Rodrigo Sancho Fernando Álvaro Gonzalo Ramiro García Pelayo
        Bermudo Nuño Diego Lope Jimeno Fortún Blasco Aznar Munio Vela
        Fadrique Enrique Alfonso Jaime Bernat Ordoño Fruela
      ],
      mountainous: %w[
        Bjorn Sigurd Gunnar Erik Leif Ragnar Sven Harald Thorvald Ivar
        Ulf Orm Knut Magnus Halfdan Haakon Ingvar Ragnald Asgeir Folkvar
        Grimr Hrólf Ketil Steinar Vidar
      ],
      forested: %w[
        Caradoc Gareth Mareddudd Cynon Peredur Urien Bedwyr Tristan Bran
        Llywelyn Cadoc Owain Geraint Emrys Hywel Rhodri Maelgwn Cadwaladr
        Iorwerth Gruffudd Einion Dafydd Cai Gwalchmai Rhys
      ],
      lowland: %w[
        Aldric Wolfram Gerhard Heinrich Dietrich Friedrich Burkhard Reinhard
        Gottfried Albrecht Konrad Siegfried Ottmar Hermann Wulfric Berthold
        Eckhard Rudolf Gunther Leopold Walther Hartmann Eberhard Ulrich Rüdiger
      ],
      maritime: %w[
        Marco Luca Nicolo Giacomo Benedetto Lorenzo Bartolomeo Matteo Giovanni
        Filippo Rinaldo Ottavio Cesare Federico Stefano Guido Aldo Taddeo
        Fausto Piero Corrado Alvise Cristoforo Dandolo Grimani
      ],
      fantasy: %w[
        Aldric Gareth Magnus Sigurd Marco Caradoc Wolfram Bjorn Omar Fernando
        Erik Llywelyn Tristan Owain Reinhard Rashid Luca Cynon Halfdan Diego
        Gunnar Geraint Ivar Bartolomeo Hywel
      ]
    }

    def for_culture(culture)
      return @@desert if culture == :desert
      return @@mountainous if culture == :mountainous
      return @@arid if culture == :arid
      return @@forested if culture == :forested
      return @@maritime if culture == :maritime
      return @@lowland if culture == :lowland
    end

    def self.data_for_fantasy

      start_words = [
        "Dún",
        "Kjer",
        "Kirchen",
        "Ash",
        "Axe",
        "Exe",
        "Usk",
        "Esk",
        "Beck",
        "Bach",
        "Ben",
        "Beinn",
        "Beann",
        "Ban",
        "Ard",
        "Berry",
        "Berg",
        "Bex",
        "Blaen",
        "Crag",
        "Craig",
        "Gart",
        "Keld",
        "Knock",
        "Ling",
        "Stow",
        "Traeth",
        "Weald",
        "Aber",
        "Ast",
        "Auch",
        "Bal",
        "Brad",
        "Caer",
        "Dal",
        "Drum",
        "Dun",
        "Dum",
        "Don",
        "Inver",
        "Kil",
        "Kin",
        "Lang",
        "Nant",
        "Nor",
        "Pont",
        "Shep",
        "Stam",
        "Stan",
        "Wraith",
        "Gloom",
        "Sud",
        "Wes",
        "Win",
        "Llan",
        "Pen",
        "Rams",
        "Lynn",
        "Ost"
      ]

      end_words = [
        "druin",
        "wald",
        "dorf",
        "stein",
        "röd",
        "rød",
        "brück",
        "veld",
        "fjord",
        "hafen",
        "heim",
        "hoff",
        "hove",
        "holm",
        "berg",
        "berg",
        "bergen",
        "afon",
        "bergh",
        "bourne",
        "burn",
        "clere",
        "combe",
        "coombe",
        "coed",
        "crag",
        "each",
        "bridge",
        "castle",
        "eig",
        "firth",
        "ford",
        "forth",
        "ffordd",
        "fos",
        "foss",
        "gate",
        "garth",
        "garde",
        "gill",
        "glyn",
        "hithe",
        "hythe",
        "holm",
        "hurst",
        "keld",
        "lough",
        "magna",
        "mawr",
        "mere",
        "more",
        "moss",
        "stow",
        "dreath",
        "tun",
        "ton",
        "wold",
        "burgh",
        "bury",
        "shaw",
        "bost",
        "carden",
        "cott",
        "dale",
        "den",
        "dean",
        "don",
        "caster",
        "field",
        "frith",
        "ham",
        "hays",
        "ing",
        "krth",
        "cheth",
        "mouth",
        "ness",
        "port",
        "stead",
        "ster",
        "thwaite",
        "wick",
        "wich",
        "wych",
        "wyke",
        "ay",
        "scar",
        "thorn",
        "drim",
        "rath",
        "toft",
        "worth",
        "worthy",
        "wardine",
        "skeld",
        "grath"
      ]

      middle_words = [
        "el", "al", "en", "an", "ar", "or", "ul", "ur", "il",
        "eth", "ath", "ith", "eld", "end", "and", "orn", "ald"
      ]

      {
        prefixes: [],
        suffixes: [],
        base_words: [],
        starts: start_words,
        middles: middle_words,
        ends: end_words,
        prefix_frequency: 0,
        suffix_frequency: 0,
        syllable_lengths: {0 => 4, 1 => 3, 2 => 1},
        source: []
      }

    end

  end

end